//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from V1Query.g by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="V1QueryParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface IV1QueryListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_selection_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_selection_token([NotNull] V1QueryParser.Attribute_selection_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_selection_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_selection_token([NotNull] V1QueryParser.Attribute_selection_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter2_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter2_token([NotNull] V1QueryParser.Filter2_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter2_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter2_token([NotNull] V1QueryParser.Filter2_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.sort_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSort_token([NotNull] V1QueryParser.Sort_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.sort_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSort_token([NotNull] V1QueryParser.Sort_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSort_token_term([NotNull] V1QueryParser.Sort_token_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSort_token_term([NotNull] V1QueryParser.Sort_token_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.asc_sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsc_sort_token_term([NotNull] V1QueryParser.Asc_sort_token_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.asc_sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsc_sort_token_term([NotNull] V1QueryParser.Asc_sort_token_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.desc_sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesc_sort_token_term([NotNull] V1QueryParser.Desc_sort_token_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.desc_sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesc_sort_token_term([NotNull] V1QueryParser.Desc_sort_token_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_definition_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_definition_token([NotNull] V1QueryParser.Attribute_definition_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_definition_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_definition_token([NotNull] V1QueryParser.Attribute_definition_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.asset_type_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsset_type_token([NotNull] V1QueryParser.Asset_type_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.asset_type_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsset_type_token([NotNull] V1QueryParser.Asset_type_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_name([NotNull] V1QueryParser.Attribute_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_name([NotNull] V1QueryParser.Attribute_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.aggregation_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregation_name([NotNull] V1QueryParser.Aggregation_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.aggregation_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregation_name([NotNull] V1QueryParser.Aggregation_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_name_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_name_part([NotNull] V1QueryParser.Attribute_name_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_name_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_name_part([NotNull] V1QueryParser.Attribute_name_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.now_only"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNow_only([NotNull] V1QueryParser.Now_onlyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.now_only"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNow_only([NotNull] V1QueryParser.Now_onlyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.downcast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDowncast([NotNull] V1QueryParser.DowncastContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.downcast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDowncast([NotNull] V1QueryParser.DowncastContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute_filter([NotNull] V1QueryParser.Attribute_filterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute_filter([NotNull] V1QueryParser.Attribute_filterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter_expression([NotNull] V1QueryParser.Filter_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter_expression([NotNull] V1QueryParser.Filter_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.grouped_filter_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGrouped_filter_term([NotNull] V1QueryParser.Grouped_filter_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.grouped_filter_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGrouped_filter_term([NotNull] V1QueryParser.Grouped_filter_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.and_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_operator([NotNull] V1QueryParser.And_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.and_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_operator([NotNull] V1QueryParser.And_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.or_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_operator([NotNull] V1QueryParser.Or_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.or_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_operator([NotNull] V1QueryParser.Or_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.simple_filter_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_filter_term([NotNull] V1QueryParser.Simple_filter_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.simple_filter_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_filter_term([NotNull] V1QueryParser.Simple_filter_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.binary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary_operator([NotNull] V1QueryParser.Binary_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.binary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary_operator([NotNull] V1QueryParser.Binary_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_operator([NotNull] V1QueryParser.Unary_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_operator([NotNull] V1QueryParser.Unary_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] V1QueryParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] V1QueryParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter_value_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter_value_list([NotNull] V1QueryParser.Filter_value_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter_value_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter_value_list([NotNull] V1QueryParser.Filter_value_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilter_value([NotNull] V1QueryParser.Filter_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilter_value([NotNull] V1QueryParser.Filter_valueContext context);
}
