//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from V1Query.g by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="V1QueryParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface IV1QueryVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.attribute_selection_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_selection_token([NotNull] V1QueryParser.Attribute_selection_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.filter2_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter2_token([NotNull] V1QueryParser.Filter2_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.sort_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSort_token([NotNull] V1QueryParser.Sort_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSort_token_term([NotNull] V1QueryParser.Sort_token_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.asc_sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsc_sort_token_term([NotNull] V1QueryParser.Asc_sort_token_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.desc_sort_token_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesc_sort_token_term([NotNull] V1QueryParser.Desc_sort_token_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.attribute_definition_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_definition_token([NotNull] V1QueryParser.Attribute_definition_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.asset_type_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsset_type_token([NotNull] V1QueryParser.Asset_type_tokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.attribute_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_name([NotNull] V1QueryParser.Attribute_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.aggregation_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregation_name([NotNull] V1QueryParser.Aggregation_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.attribute_name_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_name_part([NotNull] V1QueryParser.Attribute_name_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.now_only"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNow_only([NotNull] V1QueryParser.Now_onlyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.downcast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDowncast([NotNull] V1QueryParser.DowncastContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.attribute_filter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_filter([NotNull] V1QueryParser.Attribute_filterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.filter_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_expression([NotNull] V1QueryParser.Filter_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.grouped_filter_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouped_filter_term([NotNull] V1QueryParser.Grouped_filter_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.and_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_operator([NotNull] V1QueryParser.And_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.or_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr_operator([NotNull] V1QueryParser.Or_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.simple_filter_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_filter_term([NotNull] V1QueryParser.Simple_filter_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.binary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_operator([NotNull] V1QueryParser.Binary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] V1QueryParser.Unary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] V1QueryParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.filter_value_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_value_list([NotNull] V1QueryParser.Filter_value_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="V1QueryParser.filter_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_value([NotNull] V1QueryParser.Filter_valueContext context);
}
