//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from V1Query.g by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IV1QueryListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class V1QueryBaseListener : IV1QueryListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_selection_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_selection_token([NotNull] V1QueryParser.Attribute_selection_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_selection_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_selection_token([NotNull] V1QueryParser.Attribute_selection_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter2_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter2_token([NotNull] V1QueryParser.Filter2_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter2_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter2_token([NotNull] V1QueryParser.Filter2_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.sort_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSort_token([NotNull] V1QueryParser.Sort_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.sort_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSort_token([NotNull] V1QueryParser.Sort_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.sort_token_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSort_token_term([NotNull] V1QueryParser.Sort_token_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.sort_token_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSort_token_term([NotNull] V1QueryParser.Sort_token_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.asc_sort_token_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsc_sort_token_term([NotNull] V1QueryParser.Asc_sort_token_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.asc_sort_token_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsc_sort_token_term([NotNull] V1QueryParser.Asc_sort_token_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.desc_sort_token_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesc_sort_token_term([NotNull] V1QueryParser.Desc_sort_token_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.desc_sort_token_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesc_sort_token_term([NotNull] V1QueryParser.Desc_sort_token_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_definition_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_definition_token([NotNull] V1QueryParser.Attribute_definition_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_definition_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_definition_token([NotNull] V1QueryParser.Attribute_definition_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.asset_type_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsset_type_token([NotNull] V1QueryParser.Asset_type_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.asset_type_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsset_type_token([NotNull] V1QueryParser.Asset_type_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_name([NotNull] V1QueryParser.Attribute_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_name([NotNull] V1QueryParser.Attribute_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.aggregation_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregation_name([NotNull] V1QueryParser.Aggregation_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.aggregation_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregation_name([NotNull] V1QueryParser.Aggregation_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_name_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_name_part([NotNull] V1QueryParser.Attribute_name_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_name_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_name_part([NotNull] V1QueryParser.Attribute_name_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.now_only"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNow_only([NotNull] V1QueryParser.Now_onlyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.now_only"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNow_only([NotNull] V1QueryParser.Now_onlyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.downcast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDowncast([NotNull] V1QueryParser.DowncastContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.downcast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDowncast([NotNull] V1QueryParser.DowncastContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.attribute_filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_filter([NotNull] V1QueryParser.Attribute_filterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.attribute_filter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_filter([NotNull] V1QueryParser.Attribute_filterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter_expression([NotNull] V1QueryParser.Filter_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter_expression([NotNull] V1QueryParser.Filter_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.grouped_filter_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrouped_filter_term([NotNull] V1QueryParser.Grouped_filter_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.grouped_filter_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrouped_filter_term([NotNull] V1QueryParser.Grouped_filter_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.and_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_operator([NotNull] V1QueryParser.And_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.and_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_operator([NotNull] V1QueryParser.And_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.or_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_operator([NotNull] V1QueryParser.Or_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.or_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_operator([NotNull] V1QueryParser.Or_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.simple_filter_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_filter_term([NotNull] V1QueryParser.Simple_filter_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.simple_filter_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_filter_term([NotNull] V1QueryParser.Simple_filter_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.binary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary_operator([NotNull] V1QueryParser.Binary_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.binary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary_operator([NotNull] V1QueryParser.Binary_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_operator([NotNull] V1QueryParser.Unary_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_operator([NotNull] V1QueryParser.Unary_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] V1QueryParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] V1QueryParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter_value_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter_value_list([NotNull] V1QueryParser.Filter_value_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter_value_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter_value_list([NotNull] V1QueryParser.Filter_value_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="V1QueryParser.filter_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilter_value([NotNull] V1QueryParser.Filter_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="V1QueryParser.filter_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilter_value([NotNull] V1QueryParser.Filter_valueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
